### ISSUE TITLE
File "adafruit_bus_device/i2c_device.py", line 143, in write_then_readinto -> OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by tellingmachine** [adafruit/Adafruit_CircuitPython_INA219#21]
I am using a Metro M4 Airlift. The latest versions of Bootloader, CircuitPython (6.0.2 Alpha), ESP32 Firmware (1.6.2) and module bundle. My script runs fine for hours, but runs into this error occasionally. I added a dedicated 9V power supply. No difference. I checked the solder joints. They all look good. The board is connected to the REPL in MU on a Windows 10 laptop all the time. The script restarts fine, without the error. Here is the call stack of the exception:

 File "code.py", line 292, in <module>
  File "adafruit_ina219.py", line 222, in bus_voltage
  File "adafruit_register/i2c_bits.py", line 73, in __get__
  File "adafruit_register/i2c_bits.py", line 73, in __get__
  File "adafruit_bus_device/i2c_device.py", line 143, in write_then_readinto
OSError: [Errno 5] Input/output error

**Comment by FoamyGuy** [comment]
I think this might have been from a known issue within the bus_device library, due to a bug that existed for a few days before it got fixed. 

Please try to download a new library bundle from here: https://circuitpython.org/libraries and copy the newest version of `adafruit_bus_device` from that bundle into `lib` on your device.

Let us know if you are still seeing this issue after doing that.

**Comment by tellingmachine** [comment]
I just updated the files, but it seems that the 8/4/2020 files are identical with the ones I am using on my board. The files I was using are from 8/1/2020.

**Comment by ladyada** [comment]
try slowing down the i2c interface frequency to 100Khz, check your wiring. this is almost certainly a hardware issue not a library issue

**Comment by tellingmachine** [comment]
Thanks, that's what I am thinking too. I'll give that try.
